using System.Text;
using System.Text.Json;
using CodeGraph.Models;
using CodeGraph.Services.Models;

namespace CodeGraph.Services;

public class CodeGraphDocGenerator
{
    /// <summary>
    /// Generate repo-level CODEGRAPH.md
    /// </summary>
    public string GenerateRepoDoc(string projectName, RepoAnalysis analysis,
        IReadOnlyList<CrossRepoEdge> inboundDeps,
        IReadOnlyList<CrossRepoEdge> outboundDeps)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {projectName}");
        sb.AppendLine();
        sb.AppendLine($"> **Confidence**: {analysis.Confidence}");
        sb.AppendLine($"> **Model**: {analysis.ModelUsed}");
        sb.AppendLine($"> **Last analyzed**: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine($"> *This file is auto-generated by CodeGraph. Do not edit manually.*");
        sb.AppendLine();
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine(analysis.Summary);
        sb.AppendLine();

        var languageStats = ReadLanguageStats(analysis.RepositoryProperties);
        var notableLanguages = languageStats
            .Where(stat => stat.LocShare >= 0.10 || stat == languageStats.FirstOrDefault())
            .ToList();
        if (notableLanguages.Count > 1)
        {
            sb.AppendLine("## Languages");
            sb.AppendLine();
            foreach (var stat in notableLanguages)
            {
                sb.AppendLine(
                    $"- **{stat.Language}**: {stat.LocShare:P0} of non-blank LOC ({stat.LocNonBlank:N0} LOC, {stat.Files:N0} files)");
            }
            sb.AppendLine();
        }

        if (outboundDeps.Count > 0)
        {
            sb.AppendLine("## Dependencies (this service calls)");
            sb.AppendLine();
            foreach (var dep in outboundDeps.GroupBy(d => d.TargetProject))
            {
                sb.AppendLine($"- **{dep.Key}**");
                foreach (var edge in dep)
                    sb.AppendLine($"  - {edge.Type}: {FormatEdgeProperties(edge)}");
            }
            sb.AppendLine();
        }

        if (inboundDeps.Count > 0)
        {
            sb.AppendLine("## Dependents (these services call us)");
            sb.AppendLine();
            foreach (var dep in inboundDeps.GroupBy(d => d.SourceProject))
            {
                sb.AppendLine($"- **{dep.Key}**");
                foreach (var edge in dep)
                    sb.AppendLine($"  - {edge.Type}: {FormatEdgeProperties(edge)}");
            }
            sb.AppendLine();
        }

        sb.AppendLine("## Projects");
        sb.AppendLine();
        foreach (var project in analysis.Projects)
        {
            sb.AppendLine($"### {project.ProjectName}");
            sb.AppendLine();
            sb.AppendLine(project.Summary);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generate project-level CODEGRAPH.md
    /// </summary>
    public string GenerateProjectDoc(ProjectAnalysis analysis)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {analysis.ProjectName}");
        sb.AppendLine();
        sb.AppendLine($"> **Confidence**: {analysis.Confidence}");
        sb.AppendLine($"> **Last analyzed**: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine($"> *This file is auto-generated by CodeGraph. Do not edit manually.*");
        sb.AppendLine();
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine(analysis.Summary);
        sb.AppendLine();

        if (analysis.Endpoints.Count > 0)
        {
            sb.AppendLine("## Endpoints");
            sb.AppendLine();
            sb.AppendLine("| Method | Route | Description | Request | Response |");
            sb.AppendLine("|--------|-------|-------------|---------|----------|");
            foreach (var ep in analysis.Endpoints)
            {
                sb.AppendLine($"| {ep.HttpMethod} | `{ep.Route}` | {ep.Description} " +
                    $"| {ep.RequestModel ?? "-"} | {ep.ResponseModel ?? "-"} |");
            }
            sb.AppendLine();
        }

        if (analysis.Services.Count > 0)
        {
            sb.AppendLine("## Services");
            sb.AppendLine();
            foreach (var svc in analysis.Services)
            {
                sb.AppendLine($"### {svc.Name}");
                if (svc.InterfaceName is not null)
                    sb.AppendLine($"*Implements `{svc.InterfaceName}` ({svc.Lifetime})*");
                sb.AppendLine();
                sb.AppendLine(svc.Description);
                sb.AppendLine();
            }
        }

        if (analysis.ExternalDependencies.Count > 0)
        {
            sb.AppendLine("## External Dependencies");
            sb.AppendLine();
            foreach (var dep in analysis.ExternalDependencies)
                sb.AppendLine($"- {dep}");
            sb.AppendLine();
        }

        if (analysis.DatabaseTables.Count > 0)
        {
            sb.AppendLine("## Database Tables");
            sb.AppendLine();
            foreach (var table in analysis.DatabaseTables)
                sb.AppendLine($"- `{table}`");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string FormatEdgeProperties(CrossRepoEdge edge)
    {
        if (edge.Properties.Count == 0)
            return edge.Type.ToString();

        var parts = edge.Properties
            .Select(kv => $"{kv.Key}={kv.Value}")
            .ToList();
        return string.Join(", ", parts);
    }

    private static IReadOnlyList<LanguageStatDoc> ReadLanguageStats(
        IReadOnlyDictionary<string, object>? properties)
    {
        if (properties is null ||
            !properties.TryGetValue("languageStats", out var value) ||
            value is null)
        {
            return [];
        }

        try
        {
            using var doc = value switch
            {
                JsonElement jsonElement => JsonDocument.Parse(jsonElement.GetRawText()),
                string jsonText => JsonDocument.Parse(jsonText),
                _ => JsonDocument.Parse(JsonSerializer.Serialize(value))
            };

            if (doc.RootElement.ValueKind is not JsonValueKind.Object)
                return [];

            var stats = new List<LanguageStatDoc>();
            foreach (var language in doc.RootElement.EnumerateObject())
            {
                if (language.Value.ValueKind is not JsonValueKind.Object)
                    continue;

                stats.Add(new LanguageStatDoc(
                    language.Name,
                    GetInt32(language.Value, "files"),
                    GetInt32(language.Value, "locNonBlank"),
                    GetDouble(language.Value, "locShare")));
            }

            return stats
                .OrderByDescending(stat => stat.LocShare)
                .ThenBy(stat => stat.Language, StringComparer.OrdinalIgnoreCase)
                .ToList();
        }
        catch
        {
            return [];
        }
    }

    private static int GetInt32(JsonElement element, string name) =>
        element.TryGetProperty(name, out var value) &&
        value.ValueKind is JsonValueKind.Number &&
        value.TryGetInt32(out var result)
            ? result
            : 0;

    private static double GetDouble(JsonElement element, string name) =>
        element.TryGetProperty(name, out var value) &&
        value.ValueKind is JsonValueKind.Number &&
        value.TryGetDouble(out var result)
            ? result
            : 0;

    private sealed record LanguageStatDoc(
        string Language,
        int Files,
        int LocNonBlank,
        double LocShare);
}
