namespace CodeGraph.Data;

/// <summary>
/// Storage abstraction for wiki sections, pages, revisions, and attachments.
/// Implementations exist in CodeGraph.Data.Neo4j (Cypher).
/// </summary>
public interface IWikiStore
{
    // ── Sections ──

    Task<IReadOnlyList<WikiSectionEntity>> ListSectionsAsync();
    Task<WikiSectionEntity?> GetSectionBySlugAsync(string slug);
    Task<WikiSectionEntity?> GetSectionByIdAsync(long id);
    Task<int> CountSectionsAsync();
    Task<WikiSectionEntity> CreateSectionAsync(WikiSectionEntity entity);
    Task UpdateSectionAsync(WikiSectionEntity entity);
    Task DeleteSectionAsync(WikiSectionEntity entity);

    // ── Pages ──

    Task<WikiPageEntity?> GetPageByIdAsync(long id);
    Task<WikiPageEntity?> FindPageAsync(long sectionId, long? parentId, string slug);
    Task<IReadOnlyList<WikiPageEntity>> GetPagesBySectionAsync(long sectionId);
    Task<IReadOnlyList<WikiPageEntity>> GetAutoGeneratedPagesBySectionAsync(long sectionId);
    Task<IReadOnlyList<WikiPageEntity>> SearchPagesAsync(long sectionId, string pattern);
    Task<int> GetMaxSortOrderAsync(long sectionId, long? parentId);
    Task<WikiPageEntity> CreatePageAsync(WikiPageEntity entity);
    Task UpdatePageAsync(WikiPageEntity entity);
    Task DeletePageAsync(WikiPageEntity entity);

    // ── Revisions ──

    Task<IReadOnlyList<WikiRevisionEntity>> GetRevisionsAsync(long pageId);
    Task<WikiRevisionEntity?> GetRevisionAsync(long pageId, int revision);
    Task CreateRevisionAsync(WikiRevisionEntity entity);

    // ── Attachments ──

    Task<IReadOnlyList<WikiAttachmentEntity>> ListAttachmentsAsync(long pageId);
    Task<WikiAttachmentEntity?> GetAttachmentByIdAsync(long id);
    Task<WikiAttachmentEntity> CreateAttachmentAsync(WikiAttachmentEntity entity);
    Task DeleteAttachmentAsync(WikiAttachmentEntity entity);
}
