namespace CodeGraph.Models.Responses;

public record WikiSectionResponse(
    long Id,
    string Slug,
    string Title,
    string? Description,
    string? Icon,
    int SortOrder,
    bool IsSystem,
    bool AllowUserPages,
    bool HasRawContent);

public record WikiPageListItem(
    long Id,
    string Slug,
    string Title,
    string Author,
    int Revision,
    int Depth,
    bool IsAutoGenerated,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public record WikiPageResponse(
    long Id,
    long SectionId,
    long? ParentId,
    string Slug,
    string Title,
    string Content,
    string? RawContent,
    string Author,
    int Revision,
    int SortOrder,
    int Depth,
    bool IsAutoGenerated,
    bool HasRawContent,
    DateTime CreatedAt,
    DateTime UpdatedAt);

public record WikiTreeNode(
    long Id,
    string Slug,
    string Title,
    int Depth,
    int SortOrder,
    bool IsAutoGenerated,
    List<WikiTreeNode> Children);

public record WikiRevisionListItem(
    int Revision,
    string Title,
    string Author,
    DateTime CreatedAt);

public record WikiRevisionResponse(
    int Revision,
    string Title,
    string Content,
    string? RawContent,
    string Author,
    DateTime CreatedAt);

public record WikiAttachmentResponse(
    long Id,
    string Filename,
    string ContentType,
    long SizeBytes,
    string UploadedBy,
    string DownloadUrl,
    DateTime CreatedAt);
