ALTER TABLE embeddings
    ADD COLUMN IF NOT EXISTS model_name VARCHAR(100) NULL AFTER embedding_json,
    ADD COLUMN IF NOT EXISTS dimensions INT NULL AFTER model_name;

-- The discarded runner could crash after adding NOT NULL columns with current-looking
-- defaults but before truncating the legacy vectors. That checkpoint is indistinguishable
-- from a completed-but-unrecorded cutover followed by new writes, so conservatively retain
-- every pre-checkpoint vector while quarantining it from current-model searches. The vectors
-- can be regenerated by the normal embedding ingestion flow without any data deletion here.
UPDATE embeddings
SET model_name = 'legacy-unknown', dimensions = 0
WHERE model_name IS NULL
   OR dimensions IS NULL
   OR model_name <> 'legacy-unknown'
   OR dimensions <> 0;

ALTER TABLE embeddings
    MODIFY COLUMN model_name VARCHAR(100) NOT NULL DEFAULT 'nomic-embed-text-v1.5',
    MODIFY COLUMN dimensions INT NOT NULL DEFAULT 768;

CREATE INDEX IF NOT EXISTS idx_embeddings_model ON embeddings (model_name, dimensions);
