using CodeGraph.Data;
using CodeGraph.Models;
using CodeGraph.Tests.Extractors;
using Shouldly;

namespace CodeGraph.Tests.Services;

public class CodeGraphMcpResourcesTests
{
    [Fact]
    public async Task GetConventionsIndex_ListsConventionSlugs()
    {
        var graphStore = new InMemoryGraphStore();
        var wikiStore = new InMemoryWikiStore();
        var sut = new CodeGraphMcpResources(graphStore, wikiStore);

        var markdown = await sut.GetConventionsIndex();

        markdown.ShouldContain("## Company Conventions (1 documents)");
        markdown.ShouldContain("gateway-pattern");
        markdown.ShouldContain("codegraph://conventions/{slug}");
    }

    [Fact]
    public async Task GetProjectSummary_ReturnsFormattedSummary()
    {
        var graphStore = new InMemoryGraphStore();
        await graphStore.UpsertRepositorySummaryAsync(
            "OrdersApi",
            "Processes orders and publishes events.",
            ConfidenceLevel.High,
            "hash-1",
            "gpt-5");
        var wikiStore = new InMemoryWikiStore();
        var sut = new CodeGraphMcpResources(graphStore, wikiStore);

        var markdown = await sut.GetProjectSummary("OrdersApi");

        markdown.ShouldContain("# OrdersApi");
        markdown.ShouldContain("**Confidence:** High");
        markdown.ShouldContain("Processes orders and publishes events.");
    }

    private sealed class InMemoryWikiStore : IWikiStore
    {
        private readonly WikiSectionEntity _section = new()
        {
            Id = 10,
            Slug = "conventions",
            Title = "Conventions",
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        private readonly List<WikiPageEntity> _pages =
        [
            new WikiPageEntity
            {
                Id = 100,
                SectionId = 10,
                Slug = "gateway-pattern",
                Title = "Gateway Pattern",
                Content = "Use gateway wrappers for external HTTP calls.",
                Author = "system",
                Revision = 2,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            }
        ];

        public Task<IReadOnlyList<WikiSectionEntity>> ListSectionsAsync() => throw new NotSupportedException();
        public Task<WikiSectionEntity?> GetSectionBySlugAsync(string slug) =>
            Task.FromResult<WikiSectionEntity?>(slug == "conventions" ? _section : null);
        public Task<WikiSectionEntity?> GetSectionByIdAsync(long id) => throw new NotSupportedException();
        public Task<int> CountSectionsAsync() => throw new NotSupportedException();
        public Task<WikiSectionEntity> CreateSectionAsync(WikiSectionEntity entity) => throw new NotSupportedException();
        public Task UpdateSectionAsync(WikiSectionEntity entity) => throw new NotSupportedException();
        public Task DeleteSectionAsync(WikiSectionEntity entity) => throw new NotSupportedException();
        public Task<WikiPageEntity?> GetPageByIdAsync(long id) => throw new NotSupportedException();
        public Task<WikiPageEntity?> FindPageAsync(long sectionId, long? parentId, string slug) =>
            Task.FromResult(_pages.SingleOrDefault(x => x.SectionId == sectionId && x.ParentId == parentId && x.Slug == slug));
        public Task<IReadOnlyList<WikiPageEntity>> GetPagesBySectionAsync(long sectionId) =>
            Task.FromResult<IReadOnlyList<WikiPageEntity>>(_pages.Where(x => x.SectionId == sectionId).ToList());
        public Task<IReadOnlyList<WikiPageEntity>> GetAutoGeneratedPagesBySectionAsync(long sectionId) => throw new NotSupportedException();
        public Task<IReadOnlyList<WikiPageEntity>> SearchPagesAsync(long sectionId, string pattern) => throw new NotSupportedException();
        public Task<int> GetMaxSortOrderAsync(long sectionId, long? parentId) => throw new NotSupportedException();
        public Task<WikiPageEntity> CreatePageAsync(WikiPageEntity entity) => throw new NotSupportedException();
        public Task UpdatePageAsync(WikiPageEntity entity) => throw new NotSupportedException();
        public Task DeletePageAsync(WikiPageEntity entity) => throw new NotSupportedException();
        public Task<IReadOnlyList<WikiRevisionEntity>> GetRevisionsAsync(long pageId) => throw new NotSupportedException();
        public Task<WikiRevisionEntity?> GetRevisionAsync(long pageId, int revision) => throw new NotSupportedException();
        public Task CreateRevisionAsync(WikiRevisionEntity entity) => throw new NotSupportedException();
        public Task<IReadOnlyList<WikiAttachmentEntity>> ListAttachmentsAsync(long pageId) => throw new NotSupportedException();
        public Task<WikiAttachmentEntity?> GetAttachmentByIdAsync(long id) => throw new NotSupportedException();
        public Task<WikiAttachmentEntity> CreateAttachmentAsync(WikiAttachmentEntity entity) => throw new NotSupportedException();
        public Task DeleteAttachmentAsync(WikiAttachmentEntity entity) => throw new NotSupportedException();
    }
}
