using CodeGraph.Data;
using CodeGraph.Services;
using Microsoft.Extensions.Logging.Abstractions;
using Shouldly;

namespace CodeGraph.Tests.Services;

public class WikiSectionSeedServiceTests
{
    [Fact]
    public async Task EnsureDefaultSectionsAsync_CreatesMissingDefaults()
    {
        var store = new InMemoryWikiStore();
        var sut = new WikiSectionSeedService(store, NullLogger<WikiSectionSeedService>.Instance);

        await sut.EnsureDefaultSectionsAsync();

        var sections = await store.ListSectionsAsync();
        sections.Select(x => x.Slug).ShouldBe(
            ["general", "conventions", "skills", "agents", "mcp-documentation"],
            ignoreOrder: false);

        sections.Single(x => x.Slug == "mcp-documentation").AllowUserPages.ShouldBeFalse();
        sections.Single(x => x.Slug == "mcp-documentation").IsSystem.ShouldBeTrue();
    }

    [Fact]
    public async Task EnsureDefaultSectionsAsync_ReconcilesDriftedDefaults()
    {
        var store = new InMemoryWikiStore();
        await store.CreateSectionAsync(new WikiSectionEntity
        {
            Slug = "mcp-documentation",
            Title = "Docs",
            Description = "Wrong",
            Icon = "book",
            SortOrder = 99,
            IsSystem = false,
            AllowUserPages = true,
            HasRawContent = true,
            CreatedAt = DateTime.UtcNow.AddDays(-1),
            UpdatedAt = DateTime.UtcNow.AddDays(-1)
        });
        var sut = new WikiSectionSeedService(store, NullLogger<WikiSectionSeedService>.Instance);

        await sut.EnsureDefaultSectionsAsync();

        var section = await store.GetSectionBySlugAsync("mcp-documentation");
        section.ShouldNotBeNull();
        section.Title.ShouldBe("MCP Documentation");
        section.Description.ShouldBe("Auto-generated MCP tool documentation");
        section.Icon.ShouldBe("cpu");
        section.SortOrder.ShouldBe(4);
        section.IsSystem.ShouldBeTrue();
        section.AllowUserPages.ShouldBeFalse();
        section.HasRawContent.ShouldBeFalse();
    }

    private sealed class InMemoryWikiStore : IWikiStore
    {
        private readonly List<WikiSectionEntity> _sections = [];
        private long _nextId = 1;

        public Task<IReadOnlyList<WikiSectionEntity>> ListSectionsAsync() =>
            Task.FromResult<IReadOnlyList<WikiSectionEntity>>(_sections.OrderBy(x => x.SortOrder).ToList());

        public Task<WikiSectionEntity?> GetSectionBySlugAsync(string slug) =>
            Task.FromResult(_sections.SingleOrDefault(x => x.Slug == slug));

        public Task<WikiSectionEntity?> GetSectionByIdAsync(long id) =>
            Task.FromResult(_sections.SingleOrDefault(x => x.Id == id));

        public Task<int> CountSectionsAsync() => Task.FromResult(_sections.Count);

        public Task<WikiSectionEntity> CreateSectionAsync(WikiSectionEntity entity)
        {
            entity.Id = _nextId++;
            _sections.Add(Clone(entity));
            return Task.FromResult(entity);
        }

        public Task UpdateSectionAsync(WikiSectionEntity entity)
        {
            var index = _sections.FindIndex(x => x.Id == entity.Id);
            _sections[index] = Clone(entity);
            return Task.CompletedTask;
        }

        public Task DeleteSectionAsync(WikiSectionEntity entity) => throw new NotSupportedException();
        public Task<WikiPageEntity?> GetPageByIdAsync(long id) => throw new NotSupportedException();
        public Task<WikiPageEntity?> FindPageAsync(long sectionId, long? parentId, string slug) => throw new NotSupportedException();
        public Task<IReadOnlyList<WikiPageEntity>> GetPagesBySectionAsync(long sectionId) => throw new NotSupportedException();
        public Task<IReadOnlyList<WikiPageEntity>> GetAutoGeneratedPagesBySectionAsync(long sectionId) => throw new NotSupportedException();
        public Task<IReadOnlyList<WikiPageEntity>> SearchPagesAsync(long sectionId, string pattern) => throw new NotSupportedException();
        public Task<int> GetMaxSortOrderAsync(long sectionId, long? parentId) => throw new NotSupportedException();
        public Task<WikiPageEntity> CreatePageAsync(WikiPageEntity entity) => throw new NotSupportedException();
        public Task UpdatePageAsync(WikiPageEntity entity) => throw new NotSupportedException();
        public Task DeletePageAsync(WikiPageEntity entity) => throw new NotSupportedException();
        public Task<IReadOnlyList<WikiRevisionEntity>> GetRevisionsAsync(long pageId) => throw new NotSupportedException();
        public Task<WikiRevisionEntity?> GetRevisionAsync(long pageId, int revision) => throw new NotSupportedException();
        public Task CreateRevisionAsync(WikiRevisionEntity entity) => throw new NotSupportedException();
        public Task<IReadOnlyList<WikiAttachmentEntity>> ListAttachmentsAsync(long pageId) => throw new NotSupportedException();
        public Task<WikiAttachmentEntity?> GetAttachmentByIdAsync(long id) => throw new NotSupportedException();
        public Task<WikiAttachmentEntity> CreateAttachmentAsync(WikiAttachmentEntity entity) => throw new NotSupportedException();
        public Task DeleteAttachmentAsync(WikiAttachmentEntity entity) => throw new NotSupportedException();

        private static WikiSectionEntity Clone(WikiSectionEntity entity)
        {
            return new WikiSectionEntity
            {
                Id = entity.Id,
                Slug = entity.Slug,
                Title = entity.Title,
                Description = entity.Description,
                Icon = entity.Icon,
                SortOrder = entity.SortOrder,
                IsSystem = entity.IsSystem,
                AllowUserPages = entity.AllowUserPages,
                HasRawContent = entity.HasRawContent,
                CreatedAt = entity.CreatedAt,
                UpdatedAt = entity.UpdatedAt
            };
        }
    }
}
