using Microsoft.EntityFrameworkCore;

namespace CodeGraph.Data;

public class MySqlWikiStore(CodeGraphDbContext db) : IWikiStore
{
    // ── Sections ──

    public async Task<IReadOnlyList<WikiSectionEntity>> ListSectionsAsync()
        => await db.WikiSections.OrderBy(s => s.SortOrder).ToListAsync();

    public async Task<WikiSectionEntity?> GetSectionBySlugAsync(string slug)
        => await db.WikiSections.FirstOrDefaultAsync(s => s.Slug == slug);

    public async Task<WikiSectionEntity?> GetSectionByIdAsync(long id)
        => await db.WikiSections.FindAsync(id);

    public async Task<int> CountSectionsAsync()
        => await db.WikiSections.CountAsync();

    public async Task<WikiSectionEntity> CreateSectionAsync(WikiSectionEntity entity)
    {
        db.WikiSections.Add(entity);
        await db.SaveChangesAsync();
        return entity;
    }

    public async Task UpdateSectionAsync(WikiSectionEntity entity)
        => await db.SaveChangesAsync();

    public async Task DeleteSectionAsync(WikiSectionEntity entity)
    {
        db.WikiSections.Remove(entity);
        await db.SaveChangesAsync();
    }

    // ── Pages ──

    public async Task<WikiPageEntity?> GetPageByIdAsync(long id)
        => await db.WikiPages.FindAsync(id);

    public async Task<WikiPageEntity?> FindPageAsync(long sectionId, long? parentId, string slug)
        => await db.WikiPages.FirstOrDefaultAsync(p =>
            p.SectionId == sectionId && p.ParentId == parentId && p.Slug == slug);

    public async Task<IReadOnlyList<WikiPageEntity>> GetPagesBySectionAsync(long sectionId)
        => await db.WikiPages
            .Where(p => p.SectionId == sectionId)
            .OrderBy(p => p.SortOrder).ThenBy(p => p.Title)
            .ToListAsync();

    public async Task<IReadOnlyList<WikiPageEntity>> GetAutoGeneratedPagesBySectionAsync(long sectionId)
        => await db.WikiPages
            .Where(p => p.SectionId == sectionId && p.IsAutoGenerated)
            .ToListAsync();

    public async Task<IReadOnlyList<WikiPageEntity>> SearchPagesAsync(long sectionId, string pattern)
        => await db.WikiPages
            .Where(p => p.SectionId == sectionId
                     && (EF.Functions.Like(p.Slug, $"%{pattern}%")
                         || EF.Functions.Like(p.Title, $"%{pattern}%")))
            .ToListAsync();

    public async Task<int> GetMaxSortOrderAsync(long sectionId, long? parentId)
    {
        var max = await db.WikiPages
            .Where(p => p.SectionId == sectionId && p.ParentId == parentId)
            .MaxAsync(p => (int?)p.SortOrder);
        return max ?? -1;
    }

    public async Task<WikiPageEntity> CreatePageAsync(WikiPageEntity entity)
    {
        db.WikiPages.Add(entity);
        await db.SaveChangesAsync();
        return entity;
    }

    public async Task UpdatePageAsync(WikiPageEntity entity)
        => await db.SaveChangesAsync();

    public async Task DeletePageAsync(WikiPageEntity entity)
    {
        db.WikiPages.Remove(entity);
        await db.SaveChangesAsync();
    }

    // ── Revisions ──

    public async Task<IReadOnlyList<WikiRevisionEntity>> GetRevisionsAsync(long pageId)
        => await db.WikiRevisions
            .Where(r => r.PageId == pageId)
            .OrderByDescending(r => r.Revision)
            .ToListAsync();

    public async Task<WikiRevisionEntity?> GetRevisionAsync(long pageId, int revision)
        => await db.WikiRevisions
            .FirstOrDefaultAsync(r => r.PageId == pageId && r.Revision == revision);

    public async Task CreateRevisionAsync(WikiRevisionEntity entity)
    {
        db.WikiRevisions.Add(entity);
        await db.SaveChangesAsync();
    }

    // ── Attachments ──

    public async Task<IReadOnlyList<WikiAttachmentEntity>> ListAttachmentsAsync(long pageId)
        => await db.WikiAttachments
            .Where(a => a.PageId == pageId)
            .OrderBy(a => a.Filename)
            .ToListAsync();

    public async Task<WikiAttachmentEntity?> GetAttachmentByIdAsync(long id)
        => await db.WikiAttachments.FindAsync(id);

    public async Task<WikiAttachmentEntity> CreateAttachmentAsync(WikiAttachmentEntity entity)
    {
        db.WikiAttachments.Add(entity);
        await db.SaveChangesAsync();
        return entity;
    }

    public async Task DeleteAttachmentAsync(WikiAttachmentEntity entity)
    {
        db.WikiAttachments.Remove(entity);
        await db.SaveChangesAsync();
    }
}
