using System.ComponentModel;
using System.Reflection;
using System.Text;
using Microsoft.Extensions.Logging;
using ModelContextProtocol.Server;
using CodeGraph.Data;
using CodeGraph.Services.Assistant;

namespace CodeGraph.Services;

public class McpDocService(IWikiStore store, ILogger<McpDocService> logger) : IMcpDocService
{
    private const string AutoStartMarker = "<!-- AUTO:START - Do not edit between these markers -->";
    private const string AutoEndMarker = "<!-- AUTO:END -->";
    private const string McpSectionSlug = "mcp-documentation";

    public async Task RegenerateAsync()
    {
        var section = await store.GetSectionBySlugAsync(McpSectionSlug);
        if (section is null)
        {
            logger.LogWarning("MCP Documentation section not found — skipping doc generation");
            return;
        }

        var tools = ExtractToolMetadata();
        logger.LogInformation("Found {Count} MCP tools for documentation", tools.Count);

        var existingPages = await store.GetAutoGeneratedPagesBySectionAsync(section.Id);
        var existingBySlug = existingPages.ToDictionary(p => p.Slug);
        var processedSlugs = new HashSet<string>();

        foreach (var tool in tools)
        {
            var slug = tool.Name.Replace('_', '-');
            processedSlugs.Add(slug);

            var autoContent = BuildAutoContent(tool);

            if (existingBySlug.TryGetValue(slug, out var existing))
            {
                // Update: preserve manual content outside markers
                var newContent = ReplaceAutoSection(existing.Content, autoContent);
                if (newContent != existing.Content)
                {
                    existing.Content = newContent;
                    existing.Title = tool.Name;
                    existing.Author = "system";
                    existing.Revision++;
                    existing.UpdatedAt = DateTime.UtcNow;

                    await store.CreateRevisionAsync(new WikiRevisionEntity
                    {
                        PageId = existing.Id,
                        Revision = existing.Revision,
                        Title = existing.Title,
                        Content = existing.Content,
                        Author = "system",
                        CreatedAt = DateTime.UtcNow
                    });
                    await store.UpdatePageAsync(existing);
                }
            }
            else
            {
                // Create new page
                var content = $"{autoContent}\n\n";
                var page = new WikiPageEntity
                {
                    SectionId = section.Id,
                    Slug = slug,
                    Title = tool.Name,
                    Content = content,
                    Author = "system",
                    Revision = 1,
                    IsAutoGenerated = true,
                    Depth = 0,
                    CreatedAt = DateTime.UtcNow,
                    UpdatedAt = DateTime.UtcNow
                };
                page = await store.CreatePageAsync(page);

                await store.CreateRevisionAsync(new WikiRevisionEntity
                {
                    PageId = page.Id,
                    Revision = 1,
                    Title = page.Title,
                    Content = page.Content,
                    Author = "system",
                    CreatedAt = DateTime.UtcNow
                });
            }
        }

        // Remove pages for tools that no longer exist
        foreach (var page in existingPages.Where(p => !processedSlugs.Contains(p.Slug)))
        {
            logger.LogInformation("Removing MCP doc page for deleted tool: {Slug}", page.Slug);
            await store.DeletePageAsync(page);
        }

        logger.LogInformation("MCP documentation regeneration complete");
    }

    private static string BuildAutoContent(ToolMetadata tool)
    {
        var sb = new StringBuilder();
        sb.AppendLine(AutoStartMarker);
        sb.AppendLine($"## {tool.Name}");
        sb.AppendLine();
        sb.AppendLine($"**Description:** {tool.Description}");
        sb.AppendLine();

        if (tool.Parameters.Count > 0)
        {
            sb.AppendLine("### Parameters");
            sb.AppendLine();
            sb.AppendLine("| Name | Type | Required | Description |");
            sb.AppendLine("|------|------|----------|-------------|");
            foreach (var param in tool.Parameters)
            {
                sb.AppendLine($"| {param.Name} | {param.Type} | {(param.Required ? "Yes" : "No")} | {param.Description} |");
            }
        }

        sb.Append(AutoEndMarker);
        return sb.ToString();
    }

    private static string ReplaceAutoSection(string existingContent, string newAutoContent)
    {
        var startIdx = existingContent.IndexOf(AutoStartMarker, StringComparison.Ordinal);
        var endIdx = existingContent.IndexOf(AutoEndMarker, StringComparison.Ordinal);

        if (startIdx >= 0 && endIdx >= 0)
        {
            var before = existingContent[..startIdx];
            var after = existingContent[(endIdx + AutoEndMarker.Length)..];
            return $"{before}{newAutoContent}{after}";
        }

        // No existing markers — prepend auto content
        return $"{newAutoContent}\n\n{existingContent}";
    }

    private static List<ToolMetadata> ExtractToolMetadata()
    {
        var tools = new List<ToolMetadata>();
        var methods = typeof(CodeGraphMcpServer).GetMethods(BindingFlags.Public | BindingFlags.Instance);

        foreach (var method in methods)
        {
            var toolAttr = method.GetCustomAttribute<McpServerToolAttribute>();
            if (toolAttr is null) continue;

            var descAttr = method.GetCustomAttribute<DescriptionAttribute>();
            var parameters = method.GetParameters()
                .Where(p => p.GetCustomAttribute<DescriptionAttribute>() is not null)
                .Select(p => new ParameterMetadata(
                    p.Name ?? "",
                    p.ParameterType.Name.ToLowerInvariant(),
                    !p.HasDefaultValue,
                    p.GetCustomAttribute<DescriptionAttribute>()?.Description ?? ""))
                .ToList();

            tools.Add(new ToolMetadata(
                toolAttr.Name ?? method.Name,
                descAttr?.Description ?? "",
                parameters));
        }

        return tools.OrderBy(t => t.Name).ToList();
    }

    private record ToolMetadata(string Name, string Description, List<ParameterMetadata> Parameters);
    private record ParameterMetadata(string Name, string Type, bool Required, string Description);
}
