using System.Text.RegularExpressions;
using CodeGraph.Data;
using CodeGraph.Models.Requests;
using CodeGraph.Models.Responses;

namespace CodeGraph.Services;

public partial class WikiService(IWikiStore store) : IWikiService
{
    private const int MaxDepth = 3; // 0-indexed, so 4 levels total

    // ── Sections ──

    public async Task<IReadOnlyList<WikiSectionResponse>> ListSectionsAsync()
    {
        var sections = await store.ListSectionsAsync();
        return sections.Select(ToSectionResponse).ToList();
    }

    public async Task<WikiSectionResponse?> GetSectionAsync(string sectionSlug)
    {
        var section = await store.GetSectionBySlugAsync(sectionSlug);
        return section is null ? null : ToSectionResponse(section);
    }

    public async Task<WikiSectionResponse?> CreateSectionAsync(WikiSectionRequest request)
    {
        var slug = request.Slug ?? Slugify(request.Title);
        if (await store.GetSectionBySlugAsync(slug) is not null)
            return null;

        var entity = new WikiSectionEntity
        {
            Slug = slug,
            Title = request.Title,
            Description = request.Description,
            Icon = request.Icon,
            SortOrder = request.SortOrder ?? await store.CountSectionsAsync(),
            AllowUserPages = request.AllowUserPages,
            HasRawContent = request.HasRawContent,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };

        entity = await store.CreateSectionAsync(entity);
        return ToSectionResponse(entity);
    }

    public async Task<WikiSectionResponse?> UpdateSectionAsync(long id, WikiSectionRequest request)
    {
        var entity = await store.GetSectionByIdAsync(id);
        if (entity is null) return null;

        entity.Title = request.Title;
        entity.Description = request.Description;
        entity.Icon = request.Icon;
        if (request.SortOrder.HasValue) entity.SortOrder = request.SortOrder.Value;
        entity.AllowUserPages = request.AllowUserPages;
        entity.HasRawContent = request.HasRawContent;
        entity.UpdatedAt = DateTime.UtcNow;

        await store.UpdateSectionAsync(entity);
        return ToSectionResponse(entity);
    }

    public async Task<bool> DeleteSectionAsync(long id)
    {
        var entity = await store.GetSectionByIdAsync(id);
        if (entity is null) return false;
        if (entity.IsSystem) return false;

        await store.DeleteSectionAsync(entity);
        return true;
    }

    // ── Tree ──

    public async Task<List<WikiTreeNode>> GetSectionTreeAsync(string sectionSlug)
    {
        var section = await store.GetSectionBySlugAsync(sectionSlug);
        if (section is null) return [];

        var allPages = await store.GetPagesBySectionAsync(section.Id);
        var lookup = allPages.ToLookup(p => p.ParentId);

        List<WikiTreeNode> BuildChildren(long? parentId)
        {
            return lookup[parentId]
                .Select(p => new WikiTreeNode(p.Id, p.Slug, p.Title, p.Depth, p.SortOrder, p.IsAutoGenerated,
                    BuildChildren(p.Id)))
                .ToList();
        }

        return BuildChildren(null);
    }

    // ── Pages ──

    public async Task<WikiPageResponse?> GetPageAsync(string sectionSlug, string path)
    {
        var page = await ResolvePage(sectionSlug, path);
        if (page is null) return null;

        var section = await store.GetSectionByIdAsync(page.SectionId);
        return ToPageResponse(page, section?.HasRawContent ?? false);
    }

    public async Task<WikiPageListItem?> CreatePageAsync(string sectionSlug, WikiPageRequest request, string author)
    {
        var section = await store.GetSectionBySlugAsync(sectionSlug);
        if (section is null) return null;
        if (!section.AllowUserPages) return null;

        var slug = request.Slug ?? Slugify(request.Title);
        if (await store.FindPageAsync(section.Id, null, slug) is not null)
            return null;

        var nextSort = await store.GetMaxSortOrderAsync(section.Id, null) + 1;
        var entity = CreatePageEntity(section.Id, null, slug, request, author, 0, nextSort);
        entity = await store.CreatePageAsync(entity);
        await store.CreateRevisionAsync(CreateRevisionSnapshot(entity));
        return ToPageListItem(entity);
    }

    public async Task<WikiPageListItem?> CreateChildPageAsync(string sectionSlug, string parentPath, WikiPageRequest request, string author)
    {
        var parent = await ResolvePage(sectionSlug, parentPath);
        if (parent is null) return null;

        var section = await store.GetSectionByIdAsync(parent.SectionId);
        if (section is null || !section.AllowUserPages) return null;

        if (parent.Depth >= MaxDepth) return null;

        var slug = request.Slug ?? Slugify(request.Title);
        if (await store.FindPageAsync(parent.SectionId, parent.Id, slug) is not null)
            return null;

        var nextSort = await store.GetMaxSortOrderAsync(parent.SectionId, parent.Id) + 1;
        var entity = CreatePageEntity(parent.SectionId, parent.Id, slug, request, author, parent.Depth + 1, nextSort);
        entity = await store.CreatePageAsync(entity);
        await store.CreateRevisionAsync(CreateRevisionSnapshot(entity));
        return ToPageListItem(entity);
    }

    public async Task<WikiPageListItem?> UpdatePageAsync(string sectionSlug, string path, WikiPageRequest request, string author)
    {
        var page = await ResolvePage(sectionSlug, path);
        if (page is null) return null;

        page.Title = request.Title;
        page.Content = request.Content;
        page.RawContent = request.RawContent;
        page.Author = author;
        page.Revision++;
        if (request.SortOrder.HasValue) page.SortOrder = request.SortOrder.Value;
        page.UpdatedAt = DateTime.UtcNow;

        await store.CreateRevisionAsync(CreateRevisionSnapshot(page));
        await store.UpdatePageAsync(page);
        return ToPageListItem(page);
    }

    public async Task<bool> DeletePageAsync(string sectionSlug, string path)
    {
        var page = await ResolvePage(sectionSlug, path);
        if (page is null) return false;

        await store.DeletePageAsync(page);
        return true;
    }

    public async Task<bool> MovePageAsync(string sectionSlug, string path, WikiPageMoveRequest request)
    {
        var page = await ResolvePage(sectionSlug, path);
        if (page is null) return false;

        if (request.NewSectionId.HasValue)
        {
            var newSection = await store.GetSectionByIdAsync(request.NewSectionId.Value);
            if (newSection is null) return false;
            page.SectionId = newSection.Id;
        }

        if (request.NewParentId.HasValue)
        {
            var newParent = await store.GetPageByIdAsync(request.NewParentId.Value);
            if (newParent is null) return false;
            if (newParent.Depth >= MaxDepth) return false;
            page.ParentId = newParent.Id;
            page.Depth = newParent.Depth + 1;
        }
        else if (request.NewParentId is null && request.NewSectionId.HasValue)
        {
            page.ParentId = null;
            page.Depth = 0;
        }

        if (request.SortOrder.HasValue)
            page.SortOrder = request.SortOrder.Value;

        page.UpdatedAt = DateTime.UtcNow;
        await store.UpdatePageAsync(page);
        return true;
    }

    // ── Revisions ──

    public async Task<IReadOnlyList<WikiRevisionListItem>> GetRevisionsAsync(string sectionSlug, string path)
    {
        var page = await ResolvePage(sectionSlug, path);
        if (page is null) return [];

        var revisions = await store.GetRevisionsAsync(page.Id);
        return revisions.Select(r => new WikiRevisionListItem(r.Revision, r.Title, r.Author, r.CreatedAt)).ToList();
    }

    public async Task<WikiRevisionResponse?> GetRevisionAsync(string sectionSlug, string path, int revision)
    {
        var page = await ResolvePage(sectionSlug, path);
        if (page is null) return null;

        var rev = await store.GetRevisionAsync(page.Id, revision);
        return rev is null ? null : new WikiRevisionResponse(rev.Revision, rev.Title, rev.Content, rev.RawContent, rev.Author, rev.CreatedAt);
    }

    // ── Helpers ──

    private async Task<WikiPageEntity?> ResolvePage(string sectionSlug, string path)
    {
        var section = await store.GetSectionBySlugAsync(sectionSlug);
        if (section is null) return null;

        var slugs = path.Split('/', StringSplitOptions.RemoveEmptyEntries);
        if (slugs.Length == 0) return null;

        WikiPageEntity? current = null;
        long? parentId = null;

        foreach (var slug in slugs)
        {
            current = await store.FindPageAsync(section.Id, parentId, slug);
            if (current is null) return null;
            parentId = current.Id;
        }

        return current;
    }

    private static WikiPageEntity CreatePageEntity(long sectionId, long? parentId, string slug, WikiPageRequest request, string author, int depth, int sortOrder)
    {
        return new WikiPageEntity
        {
            SectionId = sectionId,
            ParentId = parentId,
            Slug = slug,
            Title = request.Title,
            Content = request.Content,
            RawContent = request.RawContent,
            Author = author,
            Revision = 1,
            SortOrder = request.SortOrder ?? sortOrder,
            Depth = depth,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow
        };
    }

    private static WikiRevisionEntity CreateRevisionSnapshot(WikiPageEntity page)
    {
        return new WikiRevisionEntity
        {
            PageId = page.Id,
            Revision = page.Revision,
            Title = page.Title,
            Content = page.Content,
            RawContent = page.RawContent,
            Author = page.Author,
            CreatedAt = DateTime.UtcNow
        };
    }

    private static string Slugify(string title)
    {
        var slug = title.ToLowerInvariant().Trim();
        slug = SlugInvalidChars().Replace(slug, "");
        slug = SlugWhitespace().Replace(slug, "-");
        slug = SlugMultipleDashes().Replace(slug, "-");
        return slug.Trim('-');
    }

    private static WikiSectionResponse ToSectionResponse(WikiSectionEntity e) =>
        new(e.Id, e.Slug, e.Title, e.Description, e.Icon, e.SortOrder, e.IsSystem, e.AllowUserPages, e.HasRawContent);

    private static WikiPageResponse ToPageResponse(WikiPageEntity e, bool hasRawContent) =>
        new(e.Id, e.SectionId, e.ParentId, e.Slug, e.Title, e.Content, e.RawContent,
            e.Author, e.Revision, e.SortOrder, e.Depth, e.IsAutoGenerated,
            hasRawContent, e.CreatedAt, e.UpdatedAt);

    private static WikiPageListItem ToPageListItem(WikiPageEntity e) =>
        new(e.Id, e.Slug, e.Title, e.Author, e.Revision, e.Depth, e.IsAutoGenerated, e.CreatedAt, e.UpdatedAt);

    [GeneratedRegex(@"[^a-z0-9\s-]")]
    private static partial Regex SlugInvalidChars();

    [GeneratedRegex(@"\s+")]
    private static partial Regex SlugWhitespace();

    [GeneratedRegex(@"-{2,}")]
    private static partial Regex SlugMultipleDashes();
}
